### ISSUE TITLE
Add bouncing ball animation

### ISSUE THREAD

**Issue by surajondev** [surajondev/CSS-Animation-Ride#5]
Add an animation of three balls bouncing from the ground to the `Animation`  directory.

**Comment by pavankumarraju13** [comment]
@surajondev  can you assign it to me

**Comment by surajondev** [comment]
Yep. You can work on it.

**Comment by shibam-debnath** [comment]
@surajondev can you please assign it to me ?

**Comment by shibam-debnath** [comment]
Hey @surajondev I have created one bouncing ball animation and I would love to add that here

**Comment by surajondev** [comment]
@shibam-debnath go on. Add that inside the `Animation` directory.
